name: Compilar APK de Teste

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Preparar Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Permitir execução do Gradle
        run: chmod +x gradlew

      - name: Compilar APK Debug
        run: ./gradlew assembleDebug

      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: SANTOSXZG7-APK-TESTE
          path: app/build/outputs/apk/debug/*.apk
